name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        pwd = ${{ secrets.DOCKERPW }} | sed 's/./& /g'
        echo $pwd
        echo $pwd | docker login registry-1.docker.io --username "amanpreetk" --password-stdin
        docker image build -t amanpreetk/myapp:v1 .
        docker push amanpreetk/myapp:v1
